#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01).

subFunc(){
    sub_domain=$1
    domain=$2

    record_type=$(dig "$sub_domain"."$domain" | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
    dest=$(dig "$sub_domain"."$domain" | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')
    echo "The subdomain $sub_domain is a $record_type record and points to $dest"

}
sub_d=("www" "lb-01" "web-01" "web-02")

if [ "$#" = 1 ]
then
    for sub in "${sub_d[@]}"
    do
    subFunc "$sub" "$1"
    done
elif [ "$#" = 2 ]
then
    subFunc "$2" "$1"
fi
