#!/usr/bin/env bash
# Script to configure server to redicrect to return 301 Moved permanently
apt-get -y install nginx
service nginx start
sed -i 'rewrite ^/redirect_me http://intellisoftware.tech permanent;' /etc/nginx/sites-available/default
service nginx restart
