#!/usr/bin/env bash
# Script to configure server to redicrect to return 301 Moved permanently
sudo pt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sed -i 'rewrite ^/redirect_me http://intellisoftware.tech permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
