#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# configure web-02 to be identical to web-01

sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i '11i\add_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf
sudo service nginx start
