#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd.
# script should only display:
#username
#user id
#Home directory path for the user


while IFS= read -r line; do
    echo "$line" | cut -d':' -f1,4,7
done < /etc/passwd
