#!/usr/bin/env bash
# A bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=":" read -r user pass user_id group uid_info dir cmd; do
    echo "The user $user is part of the $group gang, lives in $dir and rides $cmd. $user_id's place is protected by the passcode $pass, more info about the user here: $uid_info"
done < /etc/passwd
