#!/usr/bin/env bash
# A bash script that displays the time for 12 hours and 59 minutes
hour=0
minutes=1
while [ $hour -lt 13 ]; do
	echo Hour: $hour
	while [ $minutes -lt 60 ]; do
		echo $minutes
		(( minutes+=1 ))
	done
	(( minutes=1 ))
	(( hour+=1 ))
done
