#!/usr/bin/env bash
# A bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)
dirs="$(ls)"

for dir in $dirs; do
	echo "$dir" | cut -d "-" -f2
done
