#!/usr/bin/env bash
# A bash script that resolves loaclhost to 127.0.0.1
# and facebook.com to 8.8.8.8
sed -i 's/localhost/127.0.0.2/g' /etc/hosts
echo "8.8.8.8   facebook.com" >> /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts
